spring:
  profiles:
    active: local

---
# ----------------------------------------------------------------------
# CONFIGURATION FOR LOCAL DEVELOPMENT
# ----------------------------------------------------------------------
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/church_player_agent?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

server:
  port: 8087

app:
  storage:
    incoming-dir: ./incoming
    played-dir: ./played

---
# ----------------------------------------------------------------------
# CONFIGURATION FOR VPS SERVER
# ----------------------------------------------------------------------
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/tridarma_db?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
    username: admin
    password: C!l4ndakPuL0
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

server:
  port: 8080

app:
  storage:
    incoming-dir: /var/www/tridarma-backend/incoming
    played-dir: /var/www/tridarma-backend/played